# Generated by Django 4.2.7 on 2023-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_code',
            field=models.FileField(default='', upload_to='qr/'),
        ),
    ]
