# Generated by Django 4.2.7 on 2023-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_reserva_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr/'),
        ),
    ]
